import l from "./login";
export const Login = l;
import r from "./register";
export const Register = r;
import t from "./tabList";
export const TablList = t;
import ta from "./tabAccount";
export const TabAccount = ta;
import tp from "./tabPhoto";
export const TabPhoto = tp;
