import b from "./button";
export const Button = b;
import i from "./textInput";
export const Input = i;
import text from "./text";
export const Text = text;
import title from "./title";
export const Title = title;
import card from "./card";
export const Card = card;
import favbutton from "./favButton";
export const Favbutton = favbutton;
